# Generated by Django 5.2.11 on 2026-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('students', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructors', models.ManyToManyField(related_name='courses', to='instructors.instructor')),
                ('students', models.ManyToManyField(related_name='courses', to='students.student')),
            ],
        ),
    ]
